### ISSUE TITLE
multiprocessing issue on windows

### ISSUE THREAD

**Issue by Levitanus** [facebookincubator/Bowler#52]
Unrelated to the sh problem in windows I've caught another one:
```
Traceback (most recent call last):
  File "E:\packages\try_bowler\test.py", line 7, in <module>
    rename.dump()
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bowler\query.py", line 967, in dump
    return self.execute(write=False)
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bowler\query.py", line 957, in execute
    self.retcode = BowlerTool(fixers, **kwargs).run(self.paths)
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bowler\tool.py", line 342, in run
    self.refactor(paths)
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bowler\tool.py", line 223, in refactor
    child.start()
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Query.create_fixer.<locals>.Fixer'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "C:\Users\Levitanus\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Отказано в доступе
[Finished in 0.3s with exit code 1]
```

Original import in tool.py was replaced to import pbs as sh, but. as I understant, flow hasn't gone to the patching part of refactor

original source:
```
import bowler as bl


rename = bl.Query()
rename.select_var('value')
rename.rename('new_val')
rename.dump()
```

**Comment by jreese** [comment]
Hmm, this raises another barrier to running on Windows. Currently, Bowler will generate inline fixer classes to run the appropriate selectors, filters, and modifiers, due to the way that lib2to3 works. This is fine when using forked processes, because the child processes have the same set of locally generated classes and functions.  But Windows can only use spawned processes, requiring all classes and functions to be defined globally so that they are available in the children. 

We should instead have Bowler use a single class defined at the global scope, and build some other mechanisms for loading those fixers into the lib2to3 refactoring tool.

**Comment by thatch** [comment]
@jreese would it make sense to default to `in_process=True` on Windows for now?

**Comment by jreese** [comment]
That seems like a reasonable decision until we can find a better alternative.

**Comment by povilasb** [comment]
FYI I had the same `AttributeError: Can't pickle local object 'Query.create_fixer.<locals>.Fixer'` error on Mac OS X with Python 3.8.1.
`Query.execute(in_process=True)` helped for now :)
